language: node_js
node_js:
  - lts/*
  - node

install:
  - make --output-sync --jobs data node_modules cc-test-reporter

before_script:
  - ./cc-test-reporter before-build

script:
  - make --output-sync --jobs test lint build
  - bundlewatch

after_script:
  - make --output-sync --jobs ci

notifications:
  webhooks:
    - https://coveralls.io/webhook
    - https://www.travisbuddy.com/
